export const HOLIDAYS_GET = "HOLIDAYS_GET";
export const HOLIDAYS_SET = "HOLIDAYS_SET";
export const HOLIDAY_IN_EDIT_SET = "HOLIDAY_IN_EDIT_SET"
export const HOLIDAY_UPDATE = "HOLIDAY_UPDATE"
export const HOLIDAY_DELETE = "HOLIDAY_DELETE"
